Rails.application.routes.draw do
  get 'notes/new'
  get 'notes/create'
  get 'notes/update'
  get 'notes/edit'
  get 'notes/destroy'
  get 'notes/index'
  get 'notes/show'
  get 'shifts/new'
  get 'shifts/create'
  get 'shifts/update'
  get 'shifts/edit'
  get 'shifts/destroy'
  get 'shifts/index'
  get 'shifts/show'
  get 'availabilities/new'
  get 'availabilities/create'
  get 'availabilities/update'
  get 'availabilities/edit'
  get 'availabilities/destroy'
  get 'availabilities/index'
  get 'availabilities/show'
  get 'monitoring_schedules/new'
  get 'monitoring_schedules/create'
  get 'monitoring_schedules/update'
  get 'monitoring_schedules/edit'
  get 'monitoring_schedules/destroy'
  get 'monitoring_schedules/index'
  get 'monitoring_schedules/show'
  get 'contracts/new'
  get 'contracts/create'
  get 'contracts/update'
  get 'contracts/edit'
  get 'contracts/destroy'
  get 'contracts/index'
  get 'contracts/show'
  get 'services/new'
  get 'services/create'
  get 'services/update'
  get 'services/edit'
  get 'services/destroy'
  get 'services/index'
  get 'services/show'
  get 'engineers/new'
  get 'engineers/create'
  get 'engineers/update'
  get 'engineers/edit'
  get 'engineers/destroy'
  get 'engineers/index'
  get 'engineers/show'
  get 'engineers/index'
  get 'engineers/show'
  get 'engineers/new'
  get 'engineers/create'
  get 'engineers/update'
  get 'engineers/delete'
  get 'notes/index'
  get 'notes/show'
  get 'notes/new'
  get 'notes/create'
  get 'notes/update'
  get 'notes/delete'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end
